// Package auth implements Stage 0's JWT verification for galileo-gateway.
//
// Stage 0 uses Ed25519 (EdDSA in JWT spec) with a local dev keypair at
// kernel/auth/dev-keys/ (gitignored), generated by `make stage0-jwt-setup`.
// Stage 1 swaps the key source to Supabase JWKS without changing the
// verification logic in this file. Supabase may issue tokens under a
// different algorithm (RS256 is common); the key-format change is local
// to LoadPublicKey, not to the verification path.
package auth

import (
	"crypto/ed25519"
	"crypto/rand"
	"crypto/x509"
	"encoding/pem"
	"errors"
	"fmt"
	"os"
	"time"

	"github.com/golang-jwt/jwt/v5"
)

// Issuer is the iss claim Stage 0's gateway accepts. Stage 1's Supabase
// migration replaces this with Supabase's project URL.
const Issuer = "galileo-stage0-dev"

// Claims is the JWT claim set Galileo's gateway accepts. Mirrors the
// TenantContext proto's informational fields; the authoritative budget
// value is always re-read from Postgres per CLAUDE.md "Postgres-fresh"
// resolution (Drift-1 from the Week 3 inline-plan round).
type Claims struct {
	TenantID           string `json:"tenant_id"`
	MonthlyBudgetCents int64  `json:"monthly_budget_cents"` // informational only
	jwt.RegisteredClaims
}

// GenerateKeypair writes an Ed25519 keypair to dir as private.pem and
// public.pem. PEM blocks wrap PKCS#8 (private) and PKIX (public) DER
// encoding — the formats jwt/v5's EdDSA parser expects.
func GenerateKeypair(dir string) error {
	if err := os.MkdirAll(dir, 0o700); err != nil {
		return fmt.Errorf("mkdir keypair dir: %w", err)
	}
	pub, priv, err := ed25519.GenerateKey(rand.Reader)
	if err != nil {
		return fmt.Errorf("generate ed25519 key: %w", err)
	}
	privDER, err := x509.MarshalPKCS8PrivateKey(priv)
	if err != nil {
		return fmt.Errorf("marshal private key: %w", err)
	}
	pubDER, err := x509.MarshalPKIXPublicKey(pub)
	if err != nil {
		return fmt.Errorf("marshal public key: %w", err)
	}
	if err := writePEM(dir+"/private.pem", "PRIVATE KEY", privDER, 0o600); err != nil {
		return err
	}
	if err := writePEM(dir+"/public.pem", "PUBLIC KEY", pubDER, 0o644); err != nil {
		return err
	}
	return nil
}

// MintToken signs a JWT with the Ed25519 private key at privPath. The
// token's claims are populated from c plus sub (= tenant_id),
// iss (= Issuer), iat (now), exp (now + ttl). Stage 1's Supabase
// migration replaces this with Supabase's own minter.
func MintToken(privPath string, c Claims, ttl time.Duration) (string, error) {
	priv, err := LoadPrivateKey(privPath)
	if err != nil {
		return "", err
	}
	now := time.Now()
	c.RegisteredClaims = jwt.RegisteredClaims{
		Subject:   c.TenantID,
		Issuer:    Issuer,
		IssuedAt:  jwt.NewNumericDate(now),
		ExpiresAt: jwt.NewNumericDate(now.Add(ttl)),
	}
	tok := jwt.NewWithClaims(jwt.SigningMethodEdDSA, c)
	return tok.SignedString(priv)
}

// VerifyToken parses and validates raw against the Ed25519 public key
// at pubPath. Returns the parsed claims on success.
func VerifyToken(pubPath, raw string) (*Claims, error) {
	pub, err := LoadPublicKey(pubPath)
	if err != nil {
		return nil, err
	}
	var c Claims
	tok, err := jwt.ParseWithClaims(raw, &c, func(t *jwt.Token) (any, error) {
		if t.Method.Alg() != jwt.SigningMethodEdDSA.Alg() {
			return nil, fmt.Errorf("unexpected signing method: %v", t.Header["alg"])
		}
		return pub, nil
	}, jwt.WithIssuer(Issuer))
	if err != nil {
		return nil, fmt.Errorf("verify token: %w", err)
	}
	if !tok.Valid {
		return nil, errors.New("token invalid")
	}
	if c.TenantID == "" {
		return nil, errors.New("token missing tenant_id claim")
	}
	return &c, nil
}

// LoadPrivateKey reads a PEM/PKCS#8-encoded Ed25519 private key.
func LoadPrivateKey(path string) (ed25519.PrivateKey, error) {
	b, err := os.ReadFile(path)
	if err != nil {
		return nil, fmt.Errorf("read private key: %w", err)
	}
	block, _ := pem.Decode(b)
	if block == nil {
		return nil, errors.New("no PEM block in private key file")
	}
	parsed, err := x509.ParsePKCS8PrivateKey(block.Bytes)
	if err != nil {
		return nil, fmt.Errorf("parse PKCS#8 private key: %w", err)
	}
	priv, ok := parsed.(ed25519.PrivateKey)
	if !ok {
		return nil, fmt.Errorf("private key is not Ed25519: %T", parsed)
	}
	return priv, nil
}

// LoadPublicKey reads a PEM/PKIX-encoded Ed25519 public key.
func LoadPublicKey(path string) (ed25519.PublicKey, error) {
	b, err := os.ReadFile(path)
	if err != nil {
		return nil, fmt.Errorf("read public key: %w", err)
	}
	block, _ := pem.Decode(b)
	if block == nil {
		return nil, errors.New("no PEM block in public key file")
	}
	parsed, err := x509.ParsePKIXPublicKey(block.Bytes)
	if err != nil {
		return nil, fmt.Errorf("parse PKIX public key: %w", err)
	}
	pub, ok := parsed.(ed25519.PublicKey)
	if !ok {
		return nil, fmt.Errorf("public key is not Ed25519: %T", parsed)
	}
	return pub, nil
}

func writePEM(path, typ string, der []byte, mode os.FileMode) error {
	f, err := os.OpenFile(path, os.O_CREATE|os.O_WRONLY|os.O_TRUNC, mode)
	if err != nil {
		return fmt.Errorf("open %s: %w", path, err)
	}
	defer f.Close()
	if err := pem.Encode(f, &pem.Block{Type: typ, Bytes: der}); err != nil {
		return fmt.Errorf("encode PEM %s: %w", path, err)
	}
	return nil
}
